author: Ricardo SIGNES <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Games-Bowling-Scorecard
no_index: 
  directory: 
    - inc
    - t
version: 0.011
